services:
  n8n:
    image: ${N8N_SERVER}
    container_name: n8n
    user: ${DOCKER_USER}
    restart: unless-stopped
    ports:
      - 5678:5678
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${TZ}
      - TZ=${TZ}
      - N8N_SECURE_COOKIE=false #comment this line if you enable cloudflare access WAN
    volumes:
      - ${DATA_LOCATION}:/home/node/.n8n
      - ${FILES_LOCATION}:/files
