services:
  uptime-kuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:2.0.2
    ports:
      - 3001:3001
    volumes:
      - /PrivateDATA/UptimeKuma:/app/data
    restart: unless-stopped

