services:
  jellyfin:
    image: ${JELLYFIN_SERVER}
    container_name: jellyfin
    user: ${USER}
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - ${CONFIG_LOCATION}:/config
      - ${CACHE_LOCATION}:/cache
      - type: bind
        source: ${LIBRARY_LOCATION}
        target: /Media
    restart: 'unless-stopped'