name: immich

services:
  immich-server:
    container_name: immich_server
    image: ${IMMICH_SERVER}
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - immich.env
    environment:
      TZ: ${TZ}
    ports:
      - "2283:2283"
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ${IMMICH_ML}
    volumes:
      - ${APPDATA}/Immich/ml:/cache
    env_file:
      - immich.env
    environment:
      TZ: ${TZ}
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: ${IMMICH_REDIS}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    restart: always

  database:
    container_name: immich_postgres
    image: ${IMMICH_POSTGRES}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      TZ: ${TZ}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: unless-stopped
