services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://warden.stablerunsoftware.net
      - SIGNUPS_ALLOWED=false
    volumes:
      - /PrivateDATA/Vaultwarden/:/data/
    ports:
      - 8000:80
